apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
      - Namespace
      - ResourceQuota
      - StorageClass
      - CustomResourceDefinition
      - MutatingWebhookConfiguration
      - ServiceAccount
      - PodSecurityPolicy
      - NetworkPolicy
      - Role
      - ClusterRole
      - RoleBinding
      - ClusterRoleBinding
      - ConfigMap
      - Secret
      - Endpoints
      - Service
      - LimitRange
      - PriorityClass
      - PersistentVolume
      - PersistentVolumeClaim
      - Deployment
      - StatefulSet
      - CronJob
      - PodDisruptionBudget
    orderLast:
      - ValidatingWebhookConfiguration

resources:
  # Cert-Manager
  - ../../common/cert-manager/base
  - ../../common/cert-manager/kubeflow-issuer/base

  # Istio
  - ../../common/istio/istio-crds/base
  - ../../common/istio/istio-namespace/base
  - ../../common/istio/istio-install/overlays/oauth2-proxy

  # oauth2-proxy
  - ../../common/oauth2-proxy/overlays/m2m-dex-only

  # Dex
  - ../../common/dex/overlays/oauth2-proxy

  # KNative
  - ../../common/knative/knative-serving/overlays/gateways
  - ../../common/istio/cluster-local-gateway/base

  # Kubeflow namespace
  - ../../common/kubeflow-namespace/base

  # NetworkPolicies
  - ../../common/networkpolicies/base

  # Kubeflow Roles
  - ../../common/kubeflow-roles/base

  # Kubeflow Istio Resources
  - ../../common/istio/kubeflow-istio-resources/base
