apiVersion: v1
kind: Service
metadata:
  name: {{ include "katib-chart.fullname" . }}-controller
  labels:
    katib.kubeflow.org/component: controller
  {{- include "katib-chart.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.controller.type }}
  selector:
    katib.kubeflow.org/component: controller
    {{- include "katib-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.controller.ports | toYaml | nindent 2 }}
