apiVersion: v1
kind: Service
metadata:
  name: {{ include "katib-chart.fullname" . }}-mysql
  labels:
    katib.kubeflow.org/component: mysql
  {{- include "katib-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.type }}
  selector:
    katib.kubeflow.org/component: mysql
    {{- include "katib-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mysql.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "katib-chart.fullname" . }}-mysql
  labels:
  {{- include "katib-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysql.storageRequest | quote }}
