apiVersion: v1
kind: Service
metadata:
  name: {{ include "katib-chart.fullname" . }}-ui
  labels:
    katib.kubeflow.org/component: ui
  {{- include "katib-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.type }}
  selector:
    katib.kubeflow.org/component: ui
    {{- include "katib-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.ui.ports | toYaml | nindent 2 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "katib-chart.fullname" . }}-ui
  labels:
  {{- include "katib-chart.labels" . | nindent 4 }}
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /katib/
    rewrite:
      uri: /katib/
    route:
    - destination:
        host: katib-ui.kubeflow.svc.cluster.local
        port:
          number: 80
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "katib-chart.fullname" . }}-ui
  labels:
  {{- include "katib-chart.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
  selector:
    matchLabels:
      katib.kubeflow.org/component: ui
